In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms.median

<bound method Series.median of 0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64>

In [5]:
df.bedrooms.median()

4.0

In [6]:
df.bedrooms.fillna(df.bedrooms.median())

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

In [9]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
reg = linear_model.LinearRegression()

In [11]:
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [12]:
reg.coeff_

AttributeError: 'LinearRegression' object has no attribute 'coeff_'

In [13]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
reg.intercept_

221323.00186540408

In [15]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [16]:
from word2number import w2n

ModuleNotFoundError: No module named 'word2number'

In [17]:
df = pd.read_csv('hiring.csv')

In [18]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [19]:
df.experience = df.experience.fillna(0)

In [20]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [21]:
import math

In [24]:
df['test_score(out of 10)'].median()

8.0

In [26]:
df['test_score(out of 10)'] =df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())

In [27]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [28]:
reg = linear_model.LinearRegression()

In [34]:
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [35]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [37]:
reg.predict([[12,10,10]])

array([92002.18340611])